/**
 * Ids are generated by whoever originates an op (usually the iPad), so the same
 * op replays identically on the server and stays idempotent.
 */

const ALPHABET = '0123456789abcdefghijklmnopqrstuvwxyz'

export function newId(prefix = ''): string {
  const time = Date.now().toString(36)
  let random = ''
  const bytes = new Uint8Array(8)

  if (typeof globalThis.crypto?.getRandomValues === 'function') {
    globalThis.crypto.getRandomValues(bytes)
    for (const byte of bytes) random += ALPHABET[byte % ALPHABET.length]
  } else {
    for (let i = 0; i < 8; i++) random += ALPHABET[Math.floor(Math.random() * ALPHABET.length)]
  }

  return prefix ? `${prefix}_${time}${random}` : `${time}${random}`
}
